# Получить пользователей
GET http://localhost:3333/api/user?limit=1&page=2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJqaGRzZ3NkZ2dkaCIsImlhdCI6MTY4MTIzOTgzMiwiZXhwIjoxNjgxMjQwNzMyfQ.YscKKIjElVgiJJpKySPHLosJNnEADjDY9WfGKOSeS1g
###
