# Получить пользователей
GET http://localhost:3333/api/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsInJlZnJlc2hUb2tlbklkIjoiYmUxOWJlM2MtM2FlYi00ZmQ4LWIxNDEtYzViNmM3YTNmYmFhIiwiaWF0IjoxNjgxODI2MjgwLCJleHAiOjE2ODI0MzEwODB9.1nk6c1H2sGlhwGWX4nMhZZOr6qjssTSylUqb0OvyS70
###

# Получить друзей пользователя
GET http://localhost:3333/api/user/get-my-friends HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MjY2MjIxMCwiZXhwIjoxNjgyNjYzMTEwfQ.ePbGlvgNM3q--iQICVYsghoUXzDE9MZ5Egs1ZI8awnQ
###

# Добавить пользователя в друзья
PATCH http://localhost:3333/api/user/add-friend/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MjY2MjIxMCwiZXhwIjoxNjgyNjYzMTEwfQ.ePbGlvgNM3q--iQICVYsghoUXzDE9MZ5Egs1ZI8awnQ
###

# Удалить пользователя в из друзей
PATCH http://localhost:3333/api/user/remove-friend/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MjY2MjIxMCwiZXhwIjoxNjgyNjYzMTEwfQ.ePbGlvgNM3q--iQICVYsghoUXzDE9MZ5Egs1ZI8awnQ
###
