# Получить пользователей
GET http://localhost:3333/api/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQv9GA0LXQv9GD0YbQutC10YPQutC_0LLQsNC_0LIiLCJpYXQiOjE2Nzk5OTI3MTQsImV4cCI6MTY3OTk5MzYxNH0.E-aPwNZs4oBavscfbRhfwm9_N4RswIsTnU9JjmYLd2M
###
