# Создание нового заказа абонемент
POST http://localhost:3333/api/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY29hY2gxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwibmFtZSI6ImZnaGZnZGZnaGQiLCJpYXQiOjE2ODA4NjgyMTYsImV4cCI6MTY4MDg2OTExNn0.3YP887XOwPKWmIMt7KqxxbVg-aktvULBcaHdi8r3E4E

{
  "type": "Абонемент",
  "price": 500,
  "count": 1,
  "paymentMethod": "Mir",
  "entityId": 1
  }
###

# Получить список залов
GET http://localhost:3333/api/gym HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY29hY2gxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjgwODA2NTEwLCJleHAiOjE2ODA4MDc0MTB9.QPmQ0pIuZT4v7gLRH271GSV6sRV5gQ8SH8sCY8zMTDk
###
