# Создание новой тренировки
POST http://localhost:3333/api/training HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiY29hY2gxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwibmFtZSI6ImprZ2hzZGdkc2FkaGYiLCJpYXQiOjE2Nzk5OTM0MjcsImV4cCI6MTY3OTk5NDMyN30.CCv_oXxdoLMp55HQLSioJ1zbqIXQaTWYSwDorP3Skw4

{
  "name": "CROSSFIT",
  "backgroundImage": "",
  "level": "Любитель",
  "type": "Йога",
  "trainingDuration": "10-30",
  "price": 1000,
  "calories": 1500,
  "description": "Сложный комплекс упражнений для профессиональных атлетов на отработку показателей в классическом стиле.",
  "gender": "мужчина",
  "video": "",
  "isSpecialOffer": false
}
###

# Создание новой тренировки
GET http://localhost:3333/api/training HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiY29hY2gxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwibmFtZSI6ImprZ2hzZGdkc2FkaGYiLCJpYXQiOjE2ODAxOTY5MDAsImV4cCI6MTY4MDE5NzgwMH0.r3XG0zIPEokCVWKijXOg02-OldDdNN_M9fqAC8HF0Oc
###
