# Создание нового запроса на персональную тренировку
POST http://localhost:3333/api/personal-training HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQktCQ0JvQldCg0JjQryIsImlhdCI6MTY4Mzg4NTE3MywiZXhwIjoxNjgzODg2MDczfQ.trfH9ZaTZFY_hgepPdJOPM-EoqyDpO-dOhWMGrINtBI

{
  "targetUserId": "2"
}
###

# Редактирование запроса
PATCH http://localhost:3333/api/personal-training/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQktCQ0JvQldCg0JjQryIsImlhdCI6MTY4Mzg4NTE3MywiZXhwIjoxNjgzODg2MDczfQ.trfH9ZaTZFY_hgepPdJOPM-EoqyDpO-dOhWMGrINtBI

{
  "status": "Отклонён"
}
###

# Получение списка запросов, предназначенных мне
GET http://localhost:3333/api/personal-training/i-am-target HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQktCQ0JvQldCg0JjQryIsImlhdCI6MTY4Mzg4NTE3MywiZXhwIjoxNjgzODg2MDczfQ.trfH9ZaTZFY_hgepPdJOPM-EoqyDpO-dOhWMGrINtBI
###
