# Создание нового зала
POST http://localhost:3333/api/gym HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiY29hY2gxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwibmFtZSI6ItCY0LLQsNC9IiwiaWF0IjoxNjgzMTAzMDQxLCJleHAiOjE2ODMxMDM5NDF9.MeBvsSFkNKBpNb7EKICRTWT4zcrSwzLGBZvJDmtDqIw

{
  "name": "Super Stars",
  "location": "Пионерская",
  "isVerified": true,
  "options": ["Бассейн", "Массаж"],
  "description": "Огромный зал с отдельной зоной кроссфит. Разнообразное оборудование для занятий практически любым видом спорта. Фитнес-клуб World Sport предоставляет полный комплекс фитнес-программ, бассейны, групповой и индивидуальный тренинг, тренажерные залы, детские комнаты, 3 вида саун, SPA салоны.",
  "price": 500
  }
###

# Получить список залов
GET http://localhost:3333/api/gym HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MzEwMzA2NCwiZXhwIjoxNjgzMTAzOTY0fQ.rNObzvwWTEuEyk5Oqmg0Fq5ScsekuV1VNdMnur_Uwa4
###

# Получить список избранных залов
GET http://localhost:3333/api/gym/get-favorite-gyms HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MzEwMzA2NCwiZXhwIjoxNjgzMTAzOTY0fQ.rNObzvwWTEuEyk5Oqmg0Fq5ScsekuV1VNdMnur_Uwa4
###

# Добавить зал в избранное
PATCH http://localhost:3333/api/gym/add-favorite-gym/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MzEwMzA2NCwiZXhwIjoxNjgzMTAzOTY0fQ.rNObzvwWTEuEyk5Oqmg0Fq5ScsekuV1VNdMnur_Uwa4
###

# Удалить зал из избранного
PATCH http://localhost:3333/api/gym/remove-favorite-gym/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiLQmNCy0LDQvSIsImlhdCI6MTY4MzEwMzA2NCwiZXhwIjoxNjgzMTAzOTY0fQ.rNObzvwWTEuEyk5Oqmg0Fq5ScsekuV1VNdMnur_Uwa4
###
